/* ***************************************************
*  c2z : c2z_pass_3.c :                              *
*                                                    *
*  next error - pass3 = 1                            *
*  Copyright TCCS (c) 2015 - 2022                    *
**************************************************** */

void c2_pass_3() 
{
  if (traceflg == 1) 
  {
    strcpy(trace_1, "c2z_pass_3.c c2_pass_3 START");
    trace_rec_1();
  }

  int size = 0;
  int ret = 0;
  int ret1 = 0;
  int x = 0;
  int x2 = 0;
  int x3 = 0;
  int x4 = 0;
  int v = 0;
  int I = 0;
  int y0 = 0;
  int y1 = 0;
  int fd1_type = 0;

  char ch;
  char tfield1[VAR_LGTH];
  char tfield1a[VAR_LGTH];
  char tfield2[VAR_LGTH];

  strcpy(a_string, "*");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 generated #1");
    trace_rec_3();
  }

  strcpy(a_string, "*  This program was generated by c2z parser.");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 generated #2");
    trace_rec_3();
  }

  strcpy(a_string, "*  Generated code is for the z390 MLC.");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 generated #3");
    trace_rec_3();
  }

  strcpy(a_string, "*  Copyright (c) TCCS 2015 - 2022");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 generated #4");
    trace_rec_3();
  }

  strcpy(a_string, "*");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 generated #5");
    trace_rec_3();
  }

  strcpy(a_string, "BNO       OPSYN  JNO");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 generated #6");
    trace_rec_3();
  }

  strcpy(a_string, "BAL       OPSYN  JAS");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 generated #7");
    trace_rec_3();
  }

  strcpy(a_string, "*");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 generated #8");
    trace_rec_3();
  }

  strcpy(a_string, "          MACRO");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 generated #9");
    trace_rec_3();
  }

  strcpy(a_string, "&N        SUBENTRY");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 generated #10");
    trace_rec_3();
  }

  strcpy(a_string, "&N        CSECT");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 generated #11");
    trace_rec_3();
  }

  strcpy(a_string, "          STM    14,12,12(13)");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 generated #12");
    trace_rec_3();
  }

  strcpy(a_string, "          JAS    15,CONTINUE");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 generated #13");
    trace_rec_3();
  }

  strcpy(a_string, "          DC     18F'0'");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 generated #14");
    trace_rec_3();
  }

  strcpy(a_string, "          DC     CL8'&N'");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 generated #15");
    trace_rec_3();
  }

  strcpy(a_string, "          DC     CL8'&SYSDATE'");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 generated #16");
    trace_rec_3();
  }

  strcpy(a_string, "          DC     CL8'&SYSTIME'");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 generated #17");
    trace_rec_3();
  }

  strcpy(a_string, "CONTINUE  DS     0H");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 generated #18");
    trace_rec_3();
  }

  strcpy(a_string, "          ST     15,8(13)");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 generated #19");
    trace_rec_3();
  }

  strcpy(a_string, "          ST     13,4(15)");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 generated #20");
    trace_rec_3();
  }

  strcpy(a_string, "          LR     13,15");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 generated #21");
    trace_rec_3();
  }

  strcpy(a_string, "          USING  &N+8,13");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 generated #22");
    trace_rec_3();
  }

  strcpy(a_string, "          MEND");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 generated #23");
    trace_rec_3();
  }

  strcpy(a_string, "*");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 generated #24");
    trace_rec_3();
  }

  strcpy(a_string, "          MACRO");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 generated #25");
    trace_rec_3();
  }

  strcpy(a_string, "          SUBEXIT");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 generated #26");
    trace_rec_3();
  }

  strcpy(a_string, "          LA     15,0");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 generated #27");
    trace_rec_3();
  }

  strcpy(a_string, "          L      13,4(,13)");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 generated #28");
    trace_rec_3();
  }

  strcpy(a_string, "          L      14,12(,13)");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 generated #29");
    trace_rec_3();
  }

  strcpy(a_string, "          LM     2,12,28(13)");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 generated #30");
    trace_rec_3();
  }

  strcpy(a_string, "          BR     14");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 generated #31");
    trace_rec_3();
  }

  strcpy(a_string, "          MEND");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 generated #32");
    trace_rec_3();
  }

  strcpy(a_string, "*");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 generated #33");
    trace_rec_3();
  }

  strcpy(a_string, "*  This is a modified MVC2 macro.  Modified for baseless code");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 generated #34");
    trace_rec_3();
  }

  strcpy(a_string, "*  Modified by TCCS 2021");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 generated #35");
    trace_rec_3();
  }

  strcpy(a_string, "*  Performs a MVC operation, using Source Length NOT Target Length");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 generated #36");
    trace_rec_3();
  }

  strcpy(a_string, "*");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 generated #37");
    trace_rec_3();
  }

  strcpy(a_string, "          MACRO");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 generated #38");
    trace_rec_3();
  }

  strcpy(a_string, "&LAB      MVC2   &TARGET,&SOURCE");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 generated #39");
    trace_rec_3();
  }

  strcpy(a_string, "&LAB      LARL   R8,&SOURCE");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 generated #40");
    trace_rec_3();
  }

  strcpy(a_string, "          MVC    0(L'&SOURCE,R9),0(R8)");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 generated #41");
    trace_rec_3();
  }

  strcpy(a_string, "          MEND");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 generated #42");
    trace_rec_3();
  }

  strcpy(a_string, "*");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 generated #43");
    trace_rec_3();
  }

  strcpy(a_string, "*  This is a modified MVC2 macro.  baseless code");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 generated #45");
    trace_rec_3();
  }

  strcpy(a_string, "*  Modified by TCCS 2016");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 generated #46");
    trace_rec_3();
  }

  strcpy(a_string, "*  Performs a MVC operation, using Source Length NOT Target Length");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 generated #47");
    trace_rec_3();
  }

  strcpy(a_string, "*");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 generated #48");
    trace_rec_3();
  }

  strcpy(a_string, "          MACRO");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 generated #49");
    trace_rec_3();
  }

  strcpy(a_string, "&LAB      MVC3   &SOURCE");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 generated #50");
    trace_rec_3();
  }

  strcpy(a_string, "&LAB      LARL   R8,&SOURCE");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 generated #51");
    trace_rec_3();
  }

  strcpy(a_string, "          MVC    0(L'&SOURCE,R6),0(R8)");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 generated #52");
    trace_rec_3();
  }

  strcpy(a_string, "          MEND");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 generated #53");
    trace_rec_3();
  }

  x3 = 0;
  for (v = 0; v < gv_ct; v++) 
  {
    ret = strcmp(gw_variable[v].gv_name, "argc");
    if (ret == 0) 
    {
      x3 = 1;
    }
  }

  if (x3 == 0) 
  {
    if (gv_ct == 0) 
    {
      size = 1;
      gw_variable = malloc(size * sizeof(struct variables));
    } 
    else 
    {
      size = gv_ct + 1;
      gw_variable = realloc(gw_variable, size * sizeof(struct variables));
    }

    gw_variable[gv_ct].gv_rct = rct;
    strcpy(gw_variable[gv_ct].gv_cname, "argc");
    strcpy(gw_variable[gv_ct].gv_name, "argc");
    strcpy(gw_variable[gv_ct].gv_type, "I");
    gw_variable[gv_ct].gv_lgth = 0;
    strcpy(gw_variable[gv_ct].gv_value, null_field);
    gw_variable[gv_ct].gv_dec = 0;
    gw_variable[gv_ct].gv_id = 1;
    gv_ct++;
  }

  x3 = 0;
  for (v = 0; v < gv_ct; v++) 
  {
    ret = strcmp(gw_variable[v].gv_name, "argv");
    if (ret == 0) 
    {
      x3 = 1;
    }
  }

  tfield2[0] = '\0';
  if (x3 == 0) 
  {
    if (gv_ct == 0) 
    {
      size = 1;
      gw_variable = malloc(size * sizeof(struct variables));
    } 
    else 
    {
      size = gv_ct + 1;
      gw_variable = realloc(gw_variable, size * sizeof(struct variables));
    }

    gw_variable[gv_ct].gv_rct = rct;
    strcpy(gw_variable[gv_ct].gv_cname, "argv");
    strcpy(gw_variable[gv_ct].gv_name, "argv");
    strcpy(gw_variable[gv_ct].gv_type, "C");
    gw_variable[gv_ct].gv_lgth = 32;
    strcpy(gw_variable[gv_ct].gv_value, "32");
    gw_variable[gv_ct].gv_dec = 0;
    gw_variable[gv_ct].gv_id = 3;
    gv_ct++;
  }

  strcpy(a_string, "*");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 generated #54");
    trace_rec_3();
  }

  strcpy(a_string, "R0       EQU   0");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z_eoj.c EQUREGS #2");
    trace_rec_3();
  }

  strcpy(a_string, "R1       EQU   1");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z_eoj.c EQUREGS #2");
    trace_rec_3();
  }

  strcpy(a_string, "R2       EQU   2");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z_eoj.c EQUREGS #2");
    trace_rec_3();
  }

  strcpy(a_string, "R3       EQU   3");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z_eoj.c EQUREGS #2");
    trace_rec_3();
  }

  strcpy(a_string, "R4       EQU   4");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z_eoj.c EQUREGS #2");
    trace_rec_3();
  }

  strcpy(a_string, "R5       EQU   5");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z_eoj.c EQUREGS #2");
    trace_rec_3();
  }

  strcpy(a_string, "R6       EQU   6");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z_eoj.c EQUREGS #2");
    trace_rec_3();
  }

  strcpy(a_string, "R7       EQU   7");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z_eoj.c EQUREGS #2");
    trace_rec_3();
  }

  strcpy(a_string, "R8       EQU   8");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z_eoj.c EQUREGS #2");
    trace_rec_3();
  }

  strcpy(a_string, "R9       EQU   9");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z_eoj.c EQUREGS #2");
    trace_rec_3();
  }

  strcpy(a_string, "R10      EQU   10");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z_eoj.c EQUREGS #2");
    trace_rec_3();
  }

  strcpy(a_string, "R11      EQU   11");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z_eoj.c EQUREGS #2");
    trace_rec_3();
  }

  strcpy(a_string, "R12      EQU   12");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z_eoj.c EQUREGS #2");
    trace_rec_3();
  }

  strcpy(a_string, "R13      EQU   13");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z_eoj.c EQUREGS #2");
    trace_rec_3();
  }

  strcpy(a_string, "R14      EQU   14");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z_eoj.c EQUREGS #2");
    trace_rec_3();
  }

  strcpy(a_string, "R15      EQU   15");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z_eoj.c EQUREGS #2");
    trace_rec_3();
  }

  strcpy(a_string, "*");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 generated #54");
    trace_rec_3();
  }

  strcpy(a_string, pgm_name);
  check_length();
  strcat(a_string, "SUBENTRY");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 Generated #55");
    trace_rec_3();
  }

  strcpy(a_string, "         JLU   START");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 Generated #56");
    trace_rec_3();
  }

  strcpy(a_string, "*********************************************************");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 Generated #57");
    trace_rec_3();
  }

  strcpy(a_string, "*  open/close macro code goes here                      *");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 Generated #58");
    trace_rec_3();
  }

  strcpy(a_string, "*********************************************************");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 Generated #59");
    trace_rec_3();
  }

  if (z390 == 1) 
  {
    for (I = 0; I < f_ct; I++) 
    {
      ret = strcmp(w_file[I].f_type, "P");
      if (ret == 0) 
      {
        x4 = w_file[I].f_buf_ct;
        strcpy(a_string, "C370OPN");
        snprintf(wk_strg, sizeof(wk_strg), "%d", x4);
        strcat(a_string, wk_strg);
        check_length();
        strcat(a_string, "DS    0H");
        src_line();
        if (puncde == 1) 
        {
          strcpy(trace_1, "c2z.c pass 3 fopen #1");
          trace_rec_3();
        }

        strcpy(a_string, "         OPEN  (");
        strcat(a_string, w_file[I].f_cname);
        x = strcmp(w_file[I].f_perm, "I");
        if (x == 0) 
        {
          strcat(a_string, ",(INPUT))");
        }
        x = strcmp(w_file[I].f_perm, "O");
        if (x == 0) 
        {
          strcat(a_string, ",(OUTPUT))");
        }

        src_line();
        if (puncde == 1) 
        {
          strcpy(trace_1, "c2z.c pass 3 fopen #2");
          trace_rec_3();
        }

        strcpy(a_string, "         LARL  R9,C370PB");
        snprintf(wk_strg, sizeof(wk_strg), "%d", x4);
        strcat(a_string, wk_strg);
        src_line();
        if (puncde == 1) 
        {
          strcpy(trace_1, "c2z.c pass 3 fopen #3");
          trace_rec_3();
        }

        strcpy(a_string, "         LARL  R8,C370B1");
        src_line();
        if (puncde == 1) 
        {
          strcpy(trace_1, "c2z.c pass 3 fopen #4");
          trace_rec_3();
        }
        work_use_ct[52]++;

        strcpy(a_string, "         MVC   0(1,R9),0(R8)");
        src_line();
        if (puncde == 1) 
        {
          strcpy(trace_1, "c2z.c pass 3 fopen #5");
          trace_rec_3();
        }

        strcpy(a_string, "         MVC   1(131,R9),0(R9)");
        src_line();
        if (puncde == 1) 
        {
          strcpy(trace_1, "c2z.c pass 3 fopen #6");
          trace_rec_3();
        }

        strcpy(a_string, "         PR");
        src_line();
        if (puncde == 1) 
        {
          strcpy(trace_1, "c2z.c pass 3 fopen #7");
          trace_rec_3();
        }
      }

      strcpy(tfield1, w_file[I].f_rec_lgth);

      ch = tfield1[0];
      if (isdigit(ch))
      {
        fd1_type = 1;
      }
      if (isalpha(ch))
      {
        fd1_type = 2;
      }
      if (fd1_type == 2) 
      {
        if (gv_ct > 0) 
        {
          for (x2 = 0; x2 < gv_ct; x2++) {
            ret = strcmp(tfield1, gw_variable[x2].gv_name);
            if (ret == 0) 
            {
              strcpy(tfield1, gw_variable[x2].gv_value);
            }
          }
        }
      }

      ret = strcmp(w_file[I].f_type, "D");
      if (ret == 0) 
      {
        x4 = w_file[I].f_buf_ct;
        strcpy(a_string, "C370OPN");
        snprintf(wk_strg, sizeof(wk_strg), "%d", x4);
        strcat(a_string, wk_strg);
        check_length();
        strcat(a_string, "DS    0H");
        src_line();
        if (puncde == 1) 
        {
          strcpy(trace_1, "c2z.c pass 3 fopen #8");
          trace_rec_3();
        }

        strcpy(a_string, "         OPEN  (");
        strcat(a_string, w_file[I].f_cname);
        x = strcmp(w_file[I].f_perm, "I");
        if (x == 0) 
        {
          strcat(a_string, ",(INPUT))");
        }
        x = strcmp(w_file[I].f_perm, "O");
        if (x == 0) 
        {
          strcat(a_string, ",(OUTPUT))");
        }

        src_line();
        if (puncde == 1) 
        {
          strcpy(trace_1, "c2z.c pass 3 fopen #9");
          trace_rec_3();
        }

        strcpy(a_string, "         LARL  R9,C370PB");
        snprintf(wk_strg, sizeof(wk_strg), "%d", x4);
        strcat(a_string, wk_strg);
        src_line();
        if (puncde == 1) 
        {
          strcpy(trace_1, "c2z.c pass 3 fopen #10");
          trace_rec_3();
        }

        strcpy(a_string, "         LARL  R8,C370PB");
        snprintf(wk_strg, sizeof(wk_strg), "%d", x4);
        strcat(a_string, wk_strg);
        src_line();
        if (puncde == 1) 
        {
          strcpy(trace_1, "c2z.c pass 3 fopen #11");
          trace_rec_3();
        }

        x3 = atoi(tfield1);

        strcpy(a_string, "         XC    ");
        strcat(a_string, "0(");
        snprintf(wk_strg, sizeof(wk_strg), "%d", x3);
        strcat(a_string, wk_strg);
        strcat(a_string, ",R9),0(R8)");
        src_line();
        if (puncde == 1) 
        {
          strcpy(trace_1, "c2z.c pass 3 fopen #11");
          trace_rec_3();
        }

        strcpy(a_string, "         PR");
        src_line();
        if (puncde == 1) 
        {
          strcpy(trace_1, "c2z.c pass 3 fopen #12");
          trace_rec_3();
        }
      }
    }
  }

  strcpy(a_string, "*");
  src_line();

  y1 = 0;
  if (f_ct > 0) 
  {
    if (traceflg == 1) 
    {
      strcpy(trace_1, "c2z.c fclose");
    }

    for (I = 0; I < f_ct; I++) 
    {
      strcpy(a_string, "C370EF");
      snprintf(wk_strg, sizeof(wk_strg), "%d", w_file[I].f_buf_ct);
      y1 = w_file[I].f_buf_ct;
      strcat(a_string, wk_strg);
      check_length();
      strcat(a_string, "DS    0H");
      src_line();
      if (puncde == 1) 
      {
        strcpy(trace_1, "c2z.c fclose #1");
        trace_rec_3();
      }

      x3 = w_file[I].f_buf_ct;

      strcpy(tfield1a, w_file[I].f_cname);
      strcpy(a_string, "         CLOSE ");
      strcat(a_string, tfield1a);
      src_line();
      if (puncde == 1) 
      {
        strcpy(trace_1, "c2z.c fclose #2");
        trace_rec_3();
      }

      for (y0 = 0; y0 < fclose_ct; y0++) 
      {
        /* compare file_buf_ct vs fclose_table_buf_ct MUST MATCH */

        if (y1 == w_fclose_table[y0].cl_buf_ct) 
        {
          /* match branch back to program */
          strcpy(a_string, "         JLU   L");
          snprintf(wk_strg, sizeof(wk_strg), "%d", w_fclose_table[y0].cl_rct);
          strcat(a_string, wk_strg);
          src_line();
          if (puncde == 1) 
          {
            strcpy(trace_1, "c2z.c fclose #11");
            trace_rec_3();
          }

          strcpy(a_string, "CL");
          snprintf(wk_strg, sizeof(wk_strg), "%d", y0);
          strcat(a_string, wk_strg);
          strcat(a_string, "0");
          check_length();
          strcat(a_string, "DS    0H");
          src_line();
          if (puncde == 1) 
          {
            strcpy(trace_1, "cz2.c fclose #12");
            trace_rec_3();
          }
        }
      }

      strcpy(a_string, "         JLU   C370EXIT");
      src_line();
      if (puncde == 1) 
      {
        strcpy(trace_1, "c2z.c fclose #13");
        trace_rec_3();
      }
    }
  }

  strcpy(a_string,"******************************************************************");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c Generated #62");
    trace_rec_3();
  }

  strcpy(a_string,"*                                                                *");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c Generated #63");
    trace_rec_3();
  }

  strcpy(a_string,"* STATIC STORAGE AREA FOR CSECT - NO BASE REG REQUIRED.          *");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c Generated #64");
    trace_rec_3();
  }

  strcpy(a_string,"*                               - LARL ADDRESSING IS USED        *");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c Generated #65");
    trace_rec_3();
  }

  strcpy(a_string,"*                                                                *");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c Generated #66");
    trace_rec_3();
  }

  strcpy(a_string,"******************************************************************");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c Generated #67");
    trace_rec_3();
  }

  if (z390 == 1) 
  {
    for (I = 0; I < f_ct; I++) 
    {
      strcpy(tfield1, w_file[I].f_cname);
      ret = strcmp(w_file[I].f_type, "P");
      if (ret == 0) 
      {
        snprintf(wk_strg, sizeof(wk_strg), "%d", w_file[I].f_buf_ct);
        strcpy(a_string, "C370PB");
        strcat(a_string, wk_strg);
        check_length();
        strcat(a_string, "DC    CL132' '");
        src_line();
        if (puncde == 1) 
        {
          strcpy(trace_1, "c2z.c buffer define #1");
          trace_rec_3();
        }

        strcpy(a_string, tfield1);
        check_length();
        strcat(a_string,"DCB   DSORG=PS,                                               x");
        src_line();
        if (puncde == 1) 
        {
          strcpy(trace_1, "c2z.c buffer define #2");
          trace_rec_3();
        }

        ret1 = strcmp("O", w_file[I].f_perm);
        if (ret1 != 0) 
        {
          strcpy(a_string, "               EODAD=");
          strcat(a_string, "C370EF");
          snprintf(wk_strg, sizeof(wk_strg), "%d", w_file[I].f_buf_ct);
          strcat(a_string, wk_strg);
          strcat(a_string, ",                                          x");
          src_line();
          if (puncde == 1) 
          {
            strcpy(trace_1, "c2z.c buffer define #3");
            trace_rec_3();
          }
        }

        strcpy(a_string, "               RECFM=FT,                             "
                         "                  x");
        src_line();
        if (puncde == 1) 
        {
          strcpy(trace_1, "c2z.c buffer define #4");
          trace_rec_3();
        }

        strcpy(a_string, "               MACRF=PM,                             "
                         "                  x");
        src_line();
        if (puncde == 1) 
        {
          strcpy(trace_1, "c2z.c buffer define #5");
          trace_rec_3();
        }

        strcpy(a_string, "               SYNAD=0,                              "
                         "                  x");
        src_line();
        if (puncde == 1) 
        {
          strcpy(trace_1, "c2z.c buffer define #6");
          trace_rec_3();
        }

        strcpy(a_string, "               BLKSIZE=132,                          "
                         "                  x");
        src_line();
        if (puncde == 1) 
        {
          strcpy(trace_1, "c2z.c buffer define #7");
          trace_rec_3();
        }

        strcpy(a_string, "               LRECL=132,                            "
                         "                  x");
        src_line();
        if (puncde == 1) 
        {
          strcpy(trace_1, "c2z.c buffer define #8");
          trace_rec_3();
        }

        strcpy(a_string, "               RECORD=C370PB");
        snprintf(wk_strg, sizeof(wk_strg), "%d", w_file[I].f_buf_ct);
        strcat(a_string, wk_strg);
        src_line();
        if (puncde == 1) 
        {
          strcpy(trace_1, "c2z.c buffer define #9");
          trace_rec_3();
        }

        strcpy(a_string, "*");
        src_line();
      }

      ret = strcmp(w_file[I].f_type, "D");
      if (ret == 0) 
      {
        snprintf(wk_strg, sizeof(wk_strg), "%d", w_file[I].f_buf_ct);
        strcpy(a_string, "C370PB");
        strcat(a_string, wk_strg);
        check_length();
        strcat(a_string, "DC    CL");
        strcpy(tfield2, w_file[I].f_rec_lgth);
        ch = tfield2[0];

        if (isdigit(ch)) 
        {
          fd1_type = 1;
          x4 = atoi(w_file[I].f_rec_lgth);
        }

        if (isalpha(ch))
          fd1_type = 2;

        if (fd1_type == 2) /* variable name get value from w_variable */
        {
          if (gv_ct > 0) {
            for (x2 = 0; x2 < gv_ct; x2++) 
            {
              ret = strcmp(tfield2, gw_variable[x2].gv_name);
              if (ret == 0) 
              {
                strcpy(wk_string, gw_variable[x2].gv_value);
                x4 = atoi(gw_variable[x2].gv_value);
              }
            }
          }
        }
        snprintf(wk_strg, sizeof(wk_strg), "%d", x4);
        strcat(a_string, wk_strg);
        strcat(a_string, "' '");
        src_line();
        if (puncde == 1) 
        {
          strcpy(trace_1, "c2z.c buffer define #10");
          trace_rec_3();
        }

        strcpy(a_string, tfield1);
        check_length();
        strcat(
            a_string,
            "DCB   DSORG=PS,                                               x");
        src_line();
        if (puncde == 1) 
        {
          strcpy(trace_1, "c2z.c buffer define #11");
          trace_rec_3();
        }

        strcpy(a_string, "               EODAD=C370EF");
        /* get file buf_ct number */
        snprintf(wk_strg, sizeof(wk_strg), "%d", w_file[I].f_buf_ct);
        strcat(a_string, wk_strg);
        strcat(a_string, ",                                          x");
        src_line();
        if (puncde == 1) 
        {
          strcpy(trace_1, "c2z.c buffer define #12");
          trace_rec_3();
        }

        strcpy(a_string, "               RECFM=FT,                             "
                         "                  x");
        src_line();
        if (puncde == 1) 
        {
          strcpy(trace_1, "c2z.c buffer define #13");
          trace_rec_3();
        }

        strcpy(a_string, "               DDNAME=");
        strcat(a_string, tfield1);
        strcat(a_string, ",");
        check_continuation();
        src_line();
        if (puncde == 1) 
        {
          strcpy(trace_1, "c2z.c buffer define #14");
          trace_rec_3();
        }

        strcpy(a_string, "               MACRF=PM,                             "
                         "                  x");
        src_line();
        if (puncde == 1)
        {
          strcpy(trace_1, "c2z.c buffer define #15");
          trace_rec_3();
        }

        strcpy(a_string, "               SYNAD=0,                              "
                         "                  x");
        src_line();
        if (puncde == 1) 
        {
          strcpy(trace_1, "c2z.c buffer define #16");
          trace_rec_3();
        }

        strcpy(a_string, "               BLKSIZE=");
        snprintf(wk_strg, sizeof(wk_strg), "%d", x4);
        strcat(a_string, wk_strg);
        strcat(a_string, ",");
        check_continuation();
        src_line();
        if (puncde == 1) 
        {
          strcpy(trace_1, "c2z.c buffer define #17");
          trace_rec_3();
        }

        strcpy(a_string, "               LRECL=");
        snprintf(wk_strg, sizeof(wk_strg), "%d", x4);
        strcat(a_string, wk_strg);
        strcat(a_string, ",");
        check_continuation();
        src_line();
        if (puncde == 1) 
        {
          strcpy(trace_1, "c2z.c buffer define #18");
          trace_rec_3();
        }

        strcpy(a_string, "               RECORD=C370PB");
        snprintf(wk_strg, sizeof(wk_strg), "%d", w_file[I].f_buf_ct);
        strcat(a_string, wk_strg);
        src_line();
        if (puncde == 1) 
        {
          strcpy(trace_1, "c2z.c buffer define #19");
          trace_rec_3();
        }

        strcpy(a_string, "*");
        src_line();
        if (puncde == 1) 
        {
          strcpy(trace_1, "c2z.c buffer define #20");
          trace_rec_3();
        }
      }
    }
  }

  /* ***********************************************************
  * Punch out variable definitions.                            *
  *  w_variable[I}.v_type = C (char) are punched as CL         *
  *  w_variable[I].v_type = I (int) are punched ast PL4'0'     *
  * ********************************************************** */

/*
  c_name++;
  snprintf(wk_strg, sizeof(wk_strg), "%d", c_name);
  strcpy(c_wkname, "C37F");
  strcat(c_wkname, wk_strg);
  s = strlen(c_wkname);
  c_wkname[s] = '\0';

  if (gv_ct == 0) 
  {
    size = 1;
    gw_variable = malloc(size * sizeof(struct variables));
  } 
  else 
  {
    size = gv_ct + 1;
    gw_variable = realloc(gw_variable, size * sizeof(struct variables));
  }

  gw_variable[gv_ct].gv_rct = rct;
  strcpy(gw_variable[gv_ct].gv_cname, c_wkname);
  strcpy(gw_variable[gv_ct].gv_name, "STRLEN");
  strcpy(gw_variable[gv_ct].gv_type, "F");
  gw_variable[gv_ct].gv_lgth = 0;
  gw_variable[gv_ct].gv_current_lgth = 0;
  strcpy(gw_variable[gv_ct].gv_value, null_field);
  gw_variable[gv_ct].gv_init = 0;
  strcpy(gw_variable[gv_ct].gv_literal, null_field);
  gw_variable[gv_ct].gv_use_ct = 0;
  gw_variable[gv_ct].gv_dec = 0;
  gw_variable[gv_ct].gv_id = 2;
  gv_ct++;
*/

  strcpy(a_string,"******************************************************************");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 Generated #68");
    trace_rec_3();
  }

  strcpy(a_string,"*                                                                *");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 Generated #69");
    trace_rec_3();
  }

  strcpy(a_string,"* CODE AREA FOR CSECT -DOESN'T REQUIRE BASE REGISTER COVERAGE    *");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 Generated #70");
    trace_rec_3();
  }

  strcpy(a_string,"*                     -USE RELATIVE BRANCHES HERE                *");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 Generated #71");
    trace_rec_3();
  }

  strcpy(a_string,"*                     -DON'T CODE LITERALS HERE                  *");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 Generated #72");
    trace_rec_3();
  }

  strcpy(a_string,"*                                                                *");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 Generated #73");
    trace_rec_3();
  }

  strcpy(a_string,"******************************************************************");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 Generated #74");
    trace_rec_3();
  }

  strcpy(a_string, "START    DS    0H");
  src_line();
  if (puncde == 1) 
  {
    strcpy(trace_1, "c2z.c pass 3 Generated #75");
    trace_rec_3();
  }
}

